Repository market-karly/vanila_JS_project, pull requests merged in 2023-02, with the labels that each got.

#114 [feat] 상품리스트 상품 70% 구현 #1
  client/assets/product/bacon/detail_banner.jpg
  client/assets/product/bacon/detail_info.jpg
  client/assets/product/bacon/detail_view.jpg
  client/assets/product/bacon/thumbnail.jpg
  client/assets/product/jukkumi/detail_banner.jpg
  client/assets/product/jukkumi/detail_info.jpg
  client/assets/product/jukkumi/detail_view.jpg
  client/assets/product/jukkumi/thumbnail.jpg
  client/assets/product/kangnam/detail_banner.jpg
  client/assets/product/kangnam/detail_info.jpg
  client/assets/product/kangnam/detail_view.jpg
  client/assets/product/kangnam/thumbnail.jpg
  client/assets/product/review.svg
  client/assets/product/tangtang/detail_banner.jpg
  client/assets/product/tangtang/detail_info.jpg
  client/assets/product/tangtang/detail_view.jpg
  client/assets/product/tangtang/thumbnail.jpg
  client/assets/product/ubuho/detail_banner.jpg
  client/assets/product/ubuho/detail_info.jpg
  client/assets/product/ubuho/detail_view.jpg
  client/assets/product/ubuho/thumbnail.jpg
  client/css/main/recommend.css
  client/css/product.css
  client/css/style.css
  client/js/product.js
  client/lib/dom/index.js
  client/lib/dom/productList.js
  client/lib/utils/index.js
  client/lib/utils/parse.js
  client/product.html
  server/db/data.json
Labels: ✨ Feature

#116 [feat] 상품리스트 상품 70% 구현 #6
  client/assets/product/bacon/detail_banner.jpg
  client/assets/product/bacon/detail_info.jpg
  client/assets/product/bacon/detail_view.jpg
  client/assets/product/bacon/thumbnail.jpg
  client/assets/product/jukkumi/detail_banner.jpg
  client/assets/product/jukkumi/detail_info.jpg
  client/assets/product/jukkumi/detail_view.jpg
  client/assets/product/jukkumi/thumbnail.jpg
  client/assets/product/kangnam/detail_banner.jpg
  client/assets/product/kangnam/detail_info.jpg
  client/assets/product/kangnam/detail_view.jpg
  client/assets/product/kangnam/thumbnail.jpg
  client/assets/product/review.svg
  client/assets/product/tangtang/detail_banner.jpg
  client/assets/product/tangtang/detail_info.jpg
  client/assets/product/tangtang/detail_view.jpg
  client/assets/product/tangtang/thumbnail.jpg
  client/assets/product/ubuho/detail_banner.jpg
  client/assets/product/ubuho/detail_info.jpg
  client/assets/product/ubuho/detail_view.jpg
  client/assets/product/ubuho/thumbnail.jpg
  client/css/main/recommend.css
  client/css/product.css
  client/css/style.css
  client/js/product.js
  client/lib/dom/index.js
  client/lib/dom/productList.js
  client/lib/utils/index.js
  client/lib/utils/parse.js
  client/product.html
  server/db/data.json
Labels: ✨ Feature

#121 [feat] 메인페이지 팝업 마크업 및 닫기 기능 추가 #1
  client/assets/main/popup/popup-image.png
  client/css/main.css
  client/css/main/pop.css
  client/index.html
  client/js/main.js
  client/pop.html
Labels: ✨ Feature

#122 [feat] 상품리스트 상품 구현 완료 #6
  client/assets/product/cushion/detail_banner.jpg
  client/assets/product/cushion/detail_info.jpg
  client/assets/product/cushion/detail_veiw.jpg
  client/assets/product/cushion/thumbnail.jpg
  client/assets/product/frosh/detail_banner.jpg
  client/assets/product/frosh/detail_info.jpg
  client/assets/product/frosh/detail_view.jpg
  client/assets/product/frosh/thumbnail.jpg
  client/assets/product/queen/detail_banner.jpg
  client/assets/product/queen/detail_info.jpg
  client/assets/product/queen/detail_view.jpg
  client/assets/product/queen/thumbnail.jpg
  client/css/product/productList.css
  client/index.html
  client/js/main.js
  client/js/main/recommend.js
  client/js/product.js
  client/lib/dom/index.js
  client/lib/dom/price.js
  client/lib/dom/productList.js
  client/product.html
  server/db/data.json
Labels: ✨ Feature

#124 [chore] data.json에 products 추가 및 카테고리 브랜드 값 설정 #6
  client/assets/product/Blueberries/detail_banner.jpg
  client/assets/product/Blueberries/detail_info.jpg
  client/assets/product/Blueberries/detail_view.jpg
  client/assets/product/Blueberries/thumbnail.jpg
  client/assets/product/cushion/detail_banner.jpg
  client/assets/product/cushion/detail_veiw.jpg
  client/assets/product/cushion/detail_view.jpg
  client/assets/product/frosh/detail_view.jpg
  client/assets/product/godiva/detail_banner.jpg
  client/assets/product/godiva/detail_info.jpg
  client/assets/product/godiva/detail_view.jpg
  client/assets/product/godiva/thumbnail.jpg
  client/assets/product/granola/detail_banner.jpg
  client/assets/product/granola/detail_info.jpg
  client/assets/product/granola/detail_view.jpg
  client/assets/product/granola/thumbnail.jpg
  client/assets/product/josungalbitang/detail_banner.jpg
  client/assets/product/josungalbitang/detail_info.jpg
  client/assets/product/josungalbitang/detail_view.jpg
  client/assets/product/josungalbitang/thumbnail.jpg
  client/assets/product/lotion/detail_banner.jpg
  client/assets/product/lotion/detail_info.jpg
  client/assets/product/lotion/detail_view.jpg
  client/assets/product/lotion/thumbnail.jpg
  client/assets/product/milk/detail_banner.jpg
  client/assets/product/milk/detail_info.jpg
  client/assets/product/milk/detail_view.jpg
  client/assets/product/milk/thumbnail.jpg
  client/assets/product/picualia/detail_banner.jpg
  client/assets/product/picualia/detail_info.jpg
  client/assets/product/picualia/detail_view.jpg
  client/assets/product/picualia/thumbnail.jpg
  client/assets/product/porkrib/detail_banner.jpg
  client/assets/product/porkrib/detail_info.jpg
  client/assets/product/porkrib/detail_view.jpg
  client/assets/product/porkrib/thumbnail.jpg
  client/assets/product/shrimp/detail_banner.jpg
  client/assets/product/shrimp/detail_info.jpg
  client/assets/product/shrimp/detail_view.jpg
  client/assets/product/shrimp/thumbnail.jpg
  client/assets/product/wettissue/detail_banner.jpg
  client/assets/product/wettissue/detail_info.jpg
  client/assets/product/wettissue/detail_view.jpg
  client/assets/product/wettissue/thumbnail.jpg
  server/db/data.json
Labels: 📃 Documentation

#125 [fix] 화면 크기 줄어들때 헤더도 같이 줄어드는 오류 수정
  client/css/main/header.css
  client/index.html
  client/login.html
  client/product.html
Labels: 🐞 BugFix

#126 fix : validation 및 lighthouse 적용 후 나타나는 문제점 개선
  client/css/base.css
  client/css/main.css
  client/css/main/aside.css
  client/css/main/header.css
  client/css/product.css
  client/css/product/productNav.css
  client/index.html
  client/js/main.js
  client/js/product/ProductNav.js
  client/login.html
  client/pop.html
  client/product.html
  server/db/data.json
Labels: 🐞 BugFix

#131 [feat] 상품리스트 페이지네이션 페이지 및 페이지 이동 구현 #6
  client/css/product/productPagination.css
  client/js/main.js
  client/js/main/recommend.js
  client/js/product.js
  client/lib/dom/price.js
  client/product.html
Labels: ✨ Feature

#133 [feat] 상품리스트 페이지네이션 구현 완료 #6
  client/css/product/productPagination.css
  client/js/product.js
  client/product.html
Labels: ✨ Feature

#134 [chore] 상품리스트 페이지네이션 js 파일 이동 #6 , [feat] 상품 이미지 클릭 시 상세페이지 이동 기능 #1 #6
  client/detail.html
  client/js/detail.js
  client/js/product.js
  client/js/product/productList.js
  client/js/product/productPagination.js
  client/lib/dom/detailView.js
  client/lib/dom/index.js
  client/lib/dom/productList.js
Labels: ✨ Feature

#136 [feat] 상품리스트 페이지네이션 수정 #6
  client/js/product.js
  client/js/product/productPagination.js
  client/js/register.js
Labels: ✨ Feature

#137 feat : 상품리스트 초기화 버튼 구현 및 페이지 네이션 연동, 접근성 및 유효성 검증 완료 #6
  client/assets/icons/Icon/icon-blog.png
  client/assets/icons/Icon/icon-fb.png
  client/assets/icons/Icon/icon-instagram.png
  client/assets/icons/Icon/icon-naverpost.png
  client/assets/icons/Icon/icon-youtube.png
  client/assets/icons/Icon/logo-isms.svg
  client/assets/icons/Icon/logo-privacy.svg
  client/assets/icons/Icon/logo-tosspayments.svg
  client/assets/icons/Icon/logo-wooriBank.svg
  client/assets/main/banner/banner01.png
  client/assets/main/banner/banner01.webp
  client/assets/main/banner/banner02.png
  client/assets/main/banner/banner02.webp
  client/assets/main/banner/banner03.png
  client/assets/main/banner/banner03.webp
  client/assets/main/banner/banner05.png
  client/assets/main/banner/banner05.webp
  client/assets/main/popup/popup-image.png
  client/assets/main/popup/popup-image.webp
  client/assets/mainPage/lineBanner/line-banner.webp
  client/css/base.css
  client/css/main.css
  client/css/main/banner.css
  client/css/main/footer.css
  client/css/main/pop.css
  client/css/main/recommend.css
  client/css/pretendard.css
  client/css/product.css
  client/css/product/productNav.css
  client/detail.html
  client/font/Pretendard-Black.woff
  client/font/Pretendard-Black.woff2
  client/font/Pretendard-Bold.woff
  client/font/Pretendard-Bold.woff2
  client/font/Pretendard-ExtraBold.woff
  client/font/Pretendard-ExtraBold.woff2
  client/font/Pretendard-ExtraLight.woff
  client/font/Pretendard-ExtraLight.woff2
  client/font/Pretendard-Light.woff
  client/font/Pretendard-Light.woff2
  client/font/Pretendard-Medium.woff
  client/font/Pretendard-Medium.woff2
  client/font/Pretendard-Regular.woff
  client/font/Pretendard-Regular.woff2
  client/font/Pretendard-SemiBold.woff
  client/font/Pretendard-SemiBold.woff2
  client/font/Pretendard-Thin.woff
  client/font/Pretendard-Thin.woff2
  client/index.html
  client/js/product/ProductNav.js
  client/lib/dom/insert.js
  client/lib/dom/productList.js
  client/lib/utils/index.js
  client/lib/utils/reset.js
  client/login.html
  client/pop.html
  client/product.html
  client/register.html
Labels: 🐞 BugFix, 🗿 Chore, 🌈 Style, ✨ Feature
